### ISSUE TITLE
Errors when running Python manage.py migrate

### ISSUE THREAD

**Issue by kevinpatel55** [Diviei/nvdapi#2]
(venv) C:\Users\Kevin\nvdapi>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Kevin\nvdapi\venv\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\Kevin\nvdapi\venv\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\Kevin\nvdapi\venv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Kevin\nvdapi\venv\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Kevin\nvdapi\venv\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Kevin\nvdapi\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'corsheaders'

**Comment by Diviei** [comment]
This should be related with a problem installing any of the requirements.txt list. There was somethings that are not required at all (I hope so :P).

Check it again and let me know. I haven't touched this for a while.
